[build-system]
requires = ["flit_core >=3.2,<4", "secretum_sphinx_theme==2022.2"]
build-backend = "flit_core.buildapi"

[project]
name = "peritia"
authors = [{name = "Gerrishon Sirere", email = "scalabli@proton.me"}]
dynamic = ["version", "description"]
